export const SET_TRACKS = "SET_TRACKS"
export const SET_PLAY_TRACK = "SET_PLAY_TRACK"
export const TRACKS_IDS = "TRACKS_IDS"

export const FETCH_TRACKS_FAVORITE = "FETCH_TRACKS_FAVORITE"
export const FETCH_TRACKS_LIKES = "FETCH_TRACKS_LIKES"
export const FETCH_TRACKS_PLAYLIST = "FETCH_TRACKS_PLAYLIST"
